"""empty message

Revision ID: 3b174bf6ca0a
Revises: 31c16bf7e44f
Create Date: 2024-08-29 22:53:40.189179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b174bf6ca0a'
down_revision = '31c16bf7e44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('peopleId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planetId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('filmId', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_people_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_film_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_planet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['userId'], ['id'])
        batch_op.create_foreign_key(None, 'planet', ['planetId'], ['id'])
        batch_op.create_foreign_key(None, 'people', ['peopleId'], ['id'])
        batch_op.create_foreign_key(None, 'film', ['filmId'], ['id'])
        batch_op.drop_column('film_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('planet_id')
        batch_op.drop_column('people_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorites_planet_id_fkey', 'planet', ['planet_id'], ['id'])
        batch_op.create_foreign_key('favorites_film_id_fkey', 'film', ['film_id'], ['id'])
        batch_op.create_foreign_key('favorites_people_id_fkey', 'people', ['people_id'], ['id'])
        batch_op.drop_column('filmId')
        batch_op.drop_column('planetId')
        batch_op.drop_column('peopleId')
        batch_op.drop_column('userId')

    # ### end Alembic commands ###
